### ISSUE TITLE
Would you accept Python related modules?

### ISSUE THREAD

**Issue by johnwheeler** [miguelmota/awesome-amazon-echo#4]
Hi Miguel,

I wanted to submit a P.R. for Python related modules I've worked on, but saw you're focusing primarily on JS. Should I submit anyway, or do you want to keep it primarily NPM at this time?

Thanks,
John

**Comment by miguelmota** [comment]
@johnwheeler I don't have a problem with that, go ahead an submit a PR if you like : )
